name: Delivery Parser

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Максимальное время выполнения (2 часа)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run parser
      run: |
        python parser.py
        # Или замените на имя вашего файла, если оно другое

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: delivery-results
        path: |
          delivery_results.json
          *.log